### PR TITLE
Reexport `r2d2` and `redis` dependencies

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/sorccu/r2d2-redis/issues/15

/cc @sorccu

### CODE REVIEW

**Comment by sorccu** [comment]
I think this is a good idea overall but not sure whether the example should be updated as well. In other words I'm not sure which method we should recommend by default.

**Comment by sorccu** [comment]
@badboy Thoughts?

**Comment by badboy** [comment]
[r2d2-mysql](https://github.com/outersky/r2d2-mysql/blob/ac7a94a0a5284c102111ea9da05b830b234920cb/src/lib.rs#L55) exports it,
[r2d2-postgres](https://github.com/sfackler/r2d2-postgres/blob/8fe0923132f441abf954a0d8007f95afbfdc8f1d/src/lib.rs#L5) exports it.

So the exporting part seems reasonable to do.
I think we should also then switch over to changing the documentation. People will then use it and we get less issue reports because of version mismatches. IMO this can be done in a follow-up PR.

**Comment by Turbo87** [comment]
@badboy the docs update is already part of this PR. should I extract it to a separate PR?

**Review by badboy — APPROVED** [review]

**Comment by badboy** [comment]
That's on me for not actually checking the PR content. Of course it's fine keeping the doc change in here as well.

Approval from my side!

**Pull request merged**
